"""
etsy_launch_executor.py  —  Phase 2: Launch Executor
──────────────────────────────────────────────────────
Run:
    python scripts/etsy_launch_executor.py
    ./run.sh phase2                           # VPS shortcut

Requires:
    ANTHROPIC_API_KEY in .env
    outputs/brand_guide.md generated by Phase 1 (etsy_brand_crew.py)

Execution flow
──────────────
  Step 1 — Load brand guide
    Reads outputs/brand_guide.md (falls back to brand_guide.md in the
    project root). Raises FileNotFoundError with a clear message if missing.

  Step 2 — Resume or start fresh
    Checks outputs/executor_state.json. If it exists the run resumes from
    the last completed task — safe to re-run after a crash or API timeout.
    If missing, extract_checklist() parses the brand guide's Week 1–4
    sections into a structured task list and saves initial state to disk.

  Step 3 — Initialise outputs/master.txt
    Copied from prompts/master.txt (tracked template) on a fresh run.
    Falls back to a generated header if the template is absent.
    Not overwritten on resume so already-appended prompts are preserved.

  Step 4 — Weekly execution loop (Weeks 1–4)
    For each week, iterates every pending task and calls execute_task(),
    which asks Claude (via the Anthropic API) to generate actual Etsy
    listing content (title, tags, description) in structured format.
    After each task:
      • The listing content is appended to outputs/master.txt
      • The task is marked "completed" with a timestamp
      • A log entry is written to outputs/week_log.md
      • State is flushed to outputs/executor_state.json (crash-safe)
    A 2-second pause between tasks prevents rate-limit bursts.

  Step 5 — Week 4 feedback loop (automatic, runs after Week 4 tasks)
    Generates SEO tag recommendations based on brand guide and pipeline data.
    Output saved to outputs/feedback_report.md.

  Step 6 — Final summary
    Prints task completion count and paths for all output files.

Outputs
───────
    outputs/master.txt          — structured product listings (parsed by meta_generator.py)
    outputs/week_log.md         — timestamped task execution log
    outputs/feedback_report.md  — Week 4 tag optimisation recommendations
    outputs/executor_state.json — resumable run state

Timing: ~2–5 minutes for a full 4-week run (one API call per task).
"""

import os
import re
import json
import time
from pathlib import Path
from datetime import datetime
from dotenv import load_dotenv
import anthropic
from rich.console import Console
from rich.panel import Panel
from rich.progress import Progress, SpinnerColumn, TextColumn
from rich import print as rprint
from common import call_with_retry
from db import log_run

_ENV_FILE = Path(__file__).resolve().parent.parent / ".env"
load_dotenv(_ENV_FILE)


def _require_env(key: str) -> str:
    value = os.getenv(key)
    if not value:
        raise SystemExit(f"[error] {key} is not set. Add it to your .env file.")
    return value


console = Console()
client = anthropic.Anthropic(api_key=_require_env("ANTHROPIC_API_KEY"))

MODEL          = "claude-haiku-4-5-20251001"  # prompt-generation model (fast, cost-efficient)
BRAND_GUIDES   = (Path("outputs/brand_guide.md"), Path("brand_guide.md"))
STATE_FILE     = Path("outputs/executor_state.json")
OUTPUTS_DIR    = Path("outputs")
MASTER_TEMPLATE_FILE = Path("prompts/master.txt")
MASTER_PROMPT_FILE = OUTPUTS_DIR / "master.txt"
OUTPUTS_DIR.mkdir(exist_ok=True)


# ─── STEP 1 — LOAD BRAND GUIDE ───────────────────────────────────────────────

def load_brand_guide() -> str:
    """Read the generated brand guide from disk. Raise clearly if missing."""
    for brand_guide in BRAND_GUIDES:
        if brand_guide.exists():
            return brand_guide.read_text(encoding="utf-8")

    preferred_file = BRAND_GUIDES[0]
    fallback_file = BRAND_GUIDES[1]
    raise FileNotFoundError(
        f"Brand guide not found at {preferred_file.resolve()} or {fallback_file.resolve()}\n"
        "Run etsy_brand_crew.py first to generate it."
    )


# ─── STEP 2 — EXTRACT 30-DAY CHECKLIST ───────────────────────────────────────

def extract_checklist(brand_guide: str) -> dict[str, list[dict]]:
    """
    Parse the four weekly sections from the generated brand guide.
    Returns a dict: {"week_1": [...], "week_2": [...], ...}
    Each item: {"task": str, "tool": str | None, "status": "pending"}
    """
    week_patterns = {
        "week_1": r"Week 1.*?(?=Week 2|$)",
        "week_2": r"Week 2.*?(?=Week 3|$)",
        "week_3": r"Week 3.*?(?=Week 4|$)",
        "week_4": r"Week 4.*?(?=$)",
    }

    checklist: dict[str, list[dict]] = {}

    for week_key, pattern in week_patterns.items():
        section = re.search(pattern, brand_guide, re.DOTALL | re.IGNORECASE)
        if not section:
            checklist[week_key] = []
            continue

        block = section.group(0)

        # Extract numbered items
        items = re.findall(r"\d+\.\s+(.+?)(?=\n\d+\.|\n\n|$)", block, re.DOTALL)
        tool_match = re.search(r"\*Free Tool:\s*(.+?)\*", block)
        tool = tool_match.group(1).strip() if tool_match else None

        checklist[week_key] = [
            {
                "task":   item.strip().replace("**", "").replace("\n", " "),
                "tool":   tool,
                "status": "pending",
            }
            for item in items
        ]

    total = sum(len(v) for v in checklist.values())
    console.print(f"[dim]Extracted {total} tasks across 4 weeks from the generated brand guide[/dim]")
    return checklist


# ─── STEP 3 — STATE PERSISTENCE ───────────────────────────────────────────────

def save_state(state: dict) -> None:
    STATE_FILE.write_text(json.dumps(state, indent=2), encoding="utf-8")


def load_state() -> dict | None:
    if STATE_FILE.exists():
        return json.loads(STATE_FILE.read_text(encoding="utf-8"))
    return None


def initialize_master_prompt_file() -> None:
    """Create or reset outputs/master.txt from prompts/master.txt when available."""
    if MASTER_TEMPLATE_FILE.exists():
        template = MASTER_TEMPLATE_FILE.read_text(encoding="utf-8").rstrip()
        MASTER_PROMPT_FILE.write_text(f"{template}\n\n", encoding="utf-8")
        return

    MASTER_PROMPT_FILE.write_text(
        "# Product Listings Master File\n\n"
        f"Generated: {datetime.now().isoformat()}\n\n",
        encoding="utf-8",
    )


def append_master_prompt(week_label: str, task_number: int, task_text: str, prompt: str) -> None:
    entry = (
        f"## {week_label} · Task {task_number}\n"
        f"Task: {task_text}\n\n"
        f"{prompt}\n\n"
        "---\n\n"
    )
    with open(MASTER_PROMPT_FILE, "a", encoding="utf-8") as f:
        f.write(entry)


# ─── STEP 4 — SINGLE-TASK EXECUTOR ───────────────────────────────────────────



def execute_task(
    task_text: str,
    brand_guide: str,
    week_label: str,
    week_key: str,
) -> str:
    response = call_with_retry(lambda: client.messages.create(
        model=MODEL,
        max_tokens=1500,
        system=f"""You are an autonomous Etsy product content generator for The Freelance Command Center.

Brand guide context:
{brand_guide[:2000]}

Generate complete, ready-to-use Etsy listing content. Output MUST use this exact format:

1. [Product Name] ($[price])

**Title**: [SEO-optimized Etsy title, max 140 characters]

**Tags**: [tag1, tag2, tag3, tag4, tag5, tag6, tag7, tag8, tag9, tag10, tag11, tag12, tag13]

**Full Description**:
[200-400 word compelling product description with hook, features, benefits, and call to action]

---""",
        messages=[{"role": "user", "content": f"Generate Etsy listing content for this launch task: {task_text}"}],
    ))
    return response.content[0].text



# ─── STEP 5 — WEEKLY AGENT RUNNERS ────────────────────────────────────────────

WEEK_LABELS = {
    "week_1": "Week 1 — Storefront Setup",
    "week_2": "Week 2 — Listing Expansion",
    "week_3": "Week 3 — External Traffic",
    "week_4": "Week 4 — Optimization",
}


def run_weekly_agent(
    week_key: str,
    tasks: list[dict],
    brand_guide: str,
    state: dict,
) -> list[dict]:
    """
    Run all tasks for a given week sequentially.
    Updates and saves state after each task.
    Returns updated task list.
    """
    label = WEEK_LABELS[week_key]
    console.print(Panel(f"[bold]{label}[/bold]", style="cyan"))

    log_path = OUTPUTS_DIR / "week_log.md"

    for i, item in enumerate(tasks):
        if item["status"] == "completed":
            console.print(f"  [dim]↳ Skipping (already completed): {item['task'][:60]}[/dim]")
            continue

        task_number = i + 1
        console.print(f"\n  [bold cyan]Task {task_number}/{len(tasks)}:[/bold cyan] {item['task'][:70]}")

        with Progress(
            SpinnerColumn(),
            TextColumn("[progress.description]{task.description}"),
            transient=True,
        ) as progress:
            progress.add_task(description="Claude executing...", total=None)

            result = execute_task(
                task_text=f"Complete this task now: {item['task']}",
                brand_guide=brand_guide,
                week_label=label,
                week_key=week_key,
            )

        append_master_prompt(
            week_label=label,
            task_number=task_number,
            task_text=item["task"],
            prompt=result,
        )

        # Mark complete and log
        item["status"]    = "completed"
        item["result"]    = result[:500]
        item["completed_at"] = datetime.now().isoformat()

        log_entry = (
            f"\n## {label} · Task {task_number}\n"
            f"**Task:** {item['task']}\n"
            f"**Completed:** {item['completed_at']}\n"
            f"**Result:** {result[:300]}\n"
            f"---\n"
        )
        with open(log_path, "a", encoding="utf-8") as f:
            f.write(log_entry)

        state["checklist"][week_key] = tasks
        save_state(state)

        console.print(f"  [green]✓[/green] Task {task_number} complete")
        time.sleep(2)  # brief pause between tasks

    return tasks


# ─── STEP 6 — WEEK 4 FEEDBACK LOOP ────────────────────────────────────────────

def run_feedback_loop(brand_guide: str, state: dict) -> dict:
    """
    Week 4 SEO optimization agent.
    Analyses brand guide keywords and generates tag improvement recommendations.
    Runs fully autonomously — no browser or manual step required.
    """
    console.print(Panel("[bold]Week 4 — SEO Feedback loop running[/bold]", style="yellow"))

    completed_tasks = [
        t["task"]
        for week_tasks in state["checklist"].values()
        for t in week_tasks
        if t.get("status") == "completed"
    ]
    task_summary = "\n".join(f"- {t}" for t in completed_tasks[:10])

    response = call_with_retry(lambda: client.messages.create(
        model=MODEL,
        max_tokens=800,
        system=f"""You are an Etsy SEO optimization agent for The Freelance Command Center.
Brand guide context:
{brand_guide[:2000]}

Analyse the brand's target keywords and buyer language. Identify which tags are likely
underperforming based on competition and search intent. Suggest improvements.""",
        messages=[{
            "role": "user",
            "content": (
                f"Completed launch tasks this week:\n{task_summary}\n\n"
                "Based on the brand guide keywords and Etsy SEO best practices, identify:\n"
                "1. 3 tags likely underperforming (too broad or high competition)\n"
                "2. 3 tags likely strong performers (specific buyer intent)\n"
                "3. 3 replacement tags for the underperformers\n"
                "4. One sentence recommendation\n\n"
                'Return as JSON: {"underperforming_tags":[],"top_performing_tags":[],"replacement_tags":[],"recommendation":""}'
            ),
        }],
    ))

    result = response.content[0].text
    json_match = re.search(r"\{[\s\S]+\}", result)
    feedback_data: dict = {}

    if json_match:
        try:
            feedback_data = json.loads(json_match.group(0))
            console.print("[green]✓ SEO recommendations generated[/green]")
            rprint(feedback_data)
        except json.JSONDecodeError:
            feedback_data = {"raw_result": result}
    else:
        feedback_data = {"raw_result": result}

    state["feedback"] = {"generated_at": datetime.now().isoformat(), "data": feedback_data}
    save_state(state)

    report_path = OUTPUTS_DIR / "feedback_report.md"
    report_path.write_text(
        f"# SEO Feedback Report\n\n"
        f"Generated: {state['feedback']['generated_at']}\n\n"
        f"## Tag Analysis\n\n"
        f"```json\n{json.dumps(feedback_data, indent=2)}\n```\n\n"
        f"## Next Action\n\n"
        f"{feedback_data.get('recommendation', 'See raw result above.')}\n",
        encoding="utf-8",
    )
    console.print(f"[dim]Feedback report written to: {report_path}[/dim]")
    return feedback_data


# ─── STEP 7 — MAIN ORCHESTRATOR ───────────────────────────────────────────────

def main() -> None:
    console.print(Panel(
        "[bold]Freelance Flow — Phase 2 Autonomous Executor[/bold]\n"
        "[dim]Anthropic API · outputs/brand_guide.md → outputs/master.txt[/dim]",
        style="cyan",
    ))

    # Load brand guide
    console.print("\n[dim]Loading generated brand guide...[/dim]")
    brand_guide = load_brand_guide()

    # Resume from saved state or start fresh
    state = load_state()
    if state:
        console.print("[yellow]Resuming from saved state.[/yellow]")
        if not MASTER_PROMPT_FILE.exists():
            initialize_master_prompt_file()
    else:
        checklist = extract_checklist(brand_guide)
        state = {
            "started_at": datetime.now().isoformat(),
            "checklist":  checklist,
            "feedback":   None,
        }
        save_state(state)
        initialize_master_prompt_file()
        console.print("[green]New execution started.[/green]")

    checklist = state["checklist"]

    # ── Execute each weekly agent in sequence ──────────────────────────────
    for week_key in ["week_1", "week_2", "week_3", "week_4"]:
        tasks = checklist.get(week_key, [])
        if not tasks:
            console.print(f"[dim]No tasks found for {week_key} — skipping[/dim]")
            continue

        pending = [t for t in tasks if t["status"] != "completed"]
        if not pending:
            console.print(f"[dim]{WEEK_LABELS[week_key]} — all tasks already complete, skipping[/dim]")
            continue

        checklist[week_key] = run_weekly_agent(
            week_key=week_key,
            tasks=tasks,
            brand_guide=brand_guide,
            state=state,
        )

        # Feedback loop fires automatically after Week 4 tasks finish.
        # It generates an Etsy Stats prompt — not a live API read.
        # Claude Chrome executes the stats review when the user pastes it.
        if week_key == "week_4":
            run_feedback_loop(brand_guide=brand_guide, state=state)

        console.print(f"\n[green]✓ {WEEK_LABELS[week_key]} complete[/green]\n")
        time.sleep(3)

    # ── Final summary ──────────────────────────────────────────────────────
    total     = sum(len(v) for v in checklist.values())
    completed = sum(1 for v in checklist.values() for t in v if t["status"] == "completed")

    log_run("launch_executor", "etsy_launch_executor", "success", f"Tasks completed: {completed}/{total}")
    console.print(Panel(
        f"[bold green]Launch complete[/bold green]\n\n"
        f"Tasks completed: {completed}/{total}\n"
        f"Week log:        outputs/week_log.md\n"
        f"Master prompts:  outputs/master.txt\n"
        f"Feedback report: outputs/feedback_report.md\n"
        f"State file:      outputs/executor_state.json",
        style="green",
    ))


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        log_run("launch_executor", "etsy_launch_executor", "failed", str(exc))
        raise
