"""
etsy_autonomous.py  —  Phase 2 (alt): Richer Prompt Engine
────────────────────────────────────────────────────────────
Run:
    python scripts/etsy_autonomous.py
    ./run.sh phase2-rich                      # VPS shortcut

Requires:
    ANTHROPIC_API_KEY in .env
    outputs/brand_guide.md generated by Phase 1 (etsy_brand_crew.py)

How this differs from etsy_launch_executor.py
──────────────────────────────────────────────
This script and etsy_launch_executor.py cover the same 4-week task list but
generate prompts in different formats:

    etsy_launch_executor.py  — concise step-by-step prompt (max_tokens=1000)
                               good for quick iteration and shorter tasks

    etsy_autonomous.py       — structured 4-part prompt (max_tokens=1200):
                               1) Goal
                               2) Step-by-step browser actions
                               3) Safety constraints (no publish/purchase without confirmation)
                               4) Done checklist with proof items
                               better for complex tasks that need verification steps

Use whichever output format works best with your Claude Chrome extension workflow.
Running both on the same brand guide is safe — they write to the same
outputs/master.txt (later run appends to what the earlier wrote) and share
outputs/executor_state.json, so start fresh (delete state file) if you want
independent runs.

Execution flow
──────────────
  Step 1 — Load brand guide
    Reads outputs/brand_guide.md via load_brand_guide() from common.py.
    Falls back to brand_guide.md in project root if the outputs/ copy is missing.

  Step 2 — Resume or start fresh
    Checks outputs/executor_state.json. Resumes from last completed task if
    present; otherwise parses the brand guide with extract_checklist() and
    saves initial state.

  Step 3 — Initialise outputs/master.txt
    Seeded from prompts/master.txt on a fresh run. Not overwritten on resume.

  Step 4 — Weekly loop (Weeks 1–4)
    For each pending task, calls build_extension_prompt() which sends the task
    and the first 3200 characters of the brand guide to the API and returns the
    structured 4-part prompt.
    After each task: appends to master.txt, logs to week_log.md, saves state.

  Step 5 — Final summary
    Prints task completion count and output file paths.

Outputs
───────
    outputs/master.txt          — structured 4-part prompts for Chrome extension
    outputs/week_log.md         — timestamped task execution log
    outputs/executor_state.json — resumable run state

Timing: ~2–5 minutes for a full 4-week run.
"""

import os
import time
from pathlib import Path
from datetime import datetime
from dotenv import load_dotenv
import anthropic
from rich.console import Console
from rich.panel import Panel
from rich import print as rprint

from common import (
    call_with_retry,
    extract_checklist,
    load_brand_guide,
    load_state,
    save_state,
)

_ENV_FILE = Path(__file__).resolve().parent.parent / ".env"
load_dotenv(_ENV_FILE)

console = Console()
client  = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])

MODEL               = "claude-haiku-4-5-20251001"
_ROOT               = Path(__file__).resolve().parent.parent
BRAND_FILES         = (_ROOT / "outputs" / "brand_guide.md", _ROOT / "brand_guide.md")
STATE_FILE          = _ROOT / "outputs" / "executor_state.json"
LOG_FILE            = _ROOT / "outputs" / "week_log.md"
MASTER_TEMPLATE_FILE = _ROOT / "prompts" / "master.txt"
MASTER_PROMPT_FILE  = _ROOT / "outputs" / "master.txt"
(_ROOT / "outputs").mkdir(exist_ok=True)


def initialize_master_prompt_file() -> None:
    if MASTER_TEMPLATE_FILE.exists():
        template = MASTER_TEMPLATE_FILE.read_text(encoding="utf-8").rstrip()
        MASTER_PROMPT_FILE.write_text(f"{template}\n\n", encoding="utf-8")
        return
    MASTER_PROMPT_FILE.write_text(
        "# Master Claude Chrome Extension Prompts\n\n"
        "Use this file to execute each weekly launch task in Claude Chrome extension.\n"
        f"Generated: {datetime.now().isoformat()}\n\n",
        encoding="utf-8",
    )


def append_master_prompt(week_label: str, task_number: int, task_text: str, prompt: str) -> None:
    entry = (
        f"## {week_label} · Task {task_number}\n"
        f"Task: {task_text}\n\n"
        f"{prompt}\n\n"
        "---\n\n"
    )
    with open(MASTER_PROMPT_FILE, "a", encoding="utf-8") as f:
        f.write(entry)


def build_extension_prompt(task: str, guide: str, week: str) -> str:
    response = call_with_retry(lambda: client.messages.create(
        model=MODEL,
        max_tokens=1200,
        system=(
            "You are an Etsy launch execution planner. "
            "Generate one high-quality prompt the user can paste into the Claude Chrome extension. "
            "The prompt must include objective, exact steps, constraints, and a completion checklist."
        ),
        messages=[{
            "role": "user",
            "content": (
                f"Week: {week}\n"
                f"Task: {task}\n\n"
                "Brand guide context:\n"
                f"{guide[:3200]}\n\n"
                "Output format:\n"
                "1) Goal\n"
                "2) Step-by-step browser actions\n"
                "3) Safety constraints (no publish/purchase without confirmation)\n"
                "4) Done checklist with proof items"
            ),
        }],
    ))
    return response.content[0].text.strip()


LABELS = {
    "week_1": "Week 1 — Storefront Setup",
    "week_2": "Week 2 — Listing Expansion",
    "week_3": "Week 3 — External Traffic",
    "week_4": "Week 4 — Optimization",
}


def run_week(key: str, tasks: list, guide: str, state: dict) -> list:
    label = LABELS[key]
    console.print(Panel(f"[bold]{label}[/bold]", style="cyan"))

    for i, item in enumerate(tasks):
        if item["status"] == "completed":
            console.print(f"  [dim]↳ Skipping: {item['task'][:60]}[/dim]")
            continue

        console.print(f"\n  [bold cyan]Task {i+1}/{len(tasks)}:[/bold cyan] {item['task'][:70]}")
        console.print("  [dim]Generating Claude Chrome extension prompt...[/dim]")

        result = build_extension_prompt(item["task"], guide, label)
        rprint(f"\n[bold yellow]--- PASTE INTO CLAUDE CHROME EXTENSION ---[/bold yellow]\n{result}\n")
        append_master_prompt(label, i + 1, item["task"], result)

        item["status"]       = "completed"
        item["result"]       = result[:400]
        item["completed_at"] = datetime.now().isoformat()

        with open(LOG_FILE, "a", encoding="utf-8") as f:
            f.write(f"\n## {label} · Task {i+1}\n**Task:** {item['task']}\n**Result:** {result[:300]}\n---\n")

        state["checklist"][key] = tasks
        save_state(STATE_FILE, state)
        console.print(f"  [green]✓ Task {i+1} complete[/green]")
        time.sleep(2)

    return tasks


def main() -> None:
    console.print(Panel(
        "[bold]Creator Kit — Autonomous Executor[/bold]\n"
        f"[dim]{MODEL} · outputs/brand_guide.md[/dim]",
        style="cyan",
    ))

    guide = load_brand_guide(BRAND_FILES)

    state = load_state(STATE_FILE)
    if state:
        console.print("[yellow]Resuming from saved state.[/yellow]")
        if not MASTER_PROMPT_FILE.exists():
            initialize_master_prompt_file()
    else:
        checklist = extract_checklist(guide)
        state = {"started_at": datetime.now().isoformat(), "checklist": checklist}
        save_state(STATE_FILE, state)
        initialize_master_prompt_file()
        console.print("[green]New execution started.[/green]")

    for key in ["week_1", "week_2", "week_3", "week_4"]:
        tasks = state["checklist"].get(key, [])
        if not tasks:
            console.print(f"[dim]No tasks for {key}[/dim]")
            continue
        if all(t["status"] == "completed" for t in tasks):
            console.print(f"[dim]{LABELS[key]} already complete[/dim]")
            continue
        state["checklist"][key] = run_week(key, tasks, guide, state)
        console.print(f"\n[green]✓ {LABELS[key]} complete[/green]\n")
        time.sleep(3)

    done  = sum(1 for v in state["checklist"].values() for t in v if t["status"] == "completed")
    total = sum(len(v) for v in state["checklist"].values())
    console.print(Panel(
        f"[bold green]Launch complete[/bold green]\n\n"
        f"Tasks: {done}/{total}\n"
        f"Log: outputs/week_log.md\n"
        f"Master prompts: outputs/master.txt",
        style="green",
    ))


if __name__ == "__main__":
    main()
