"""
etsy_autonomous.py  —  Phase 2 (alt): Richer Listing Generator
────────────────────────────────────────────────────────────────
Run:
    python scripts/etsy_autonomous.py
    ./run.sh phase2-rich                      # VPS shortcut

Requires:
    ANTHROPIC_API_KEY in .env
    outputs/brand_guide.md generated by Phase 1 (etsy_brand_crew.py)

How this differs from etsy_launch_executor.py
──────────────────────────────────────────────
Both scripts generate Etsy listing content from the brand guide, but in different
detail levels:

    etsy_launch_executor.py  — concise listing (max_tokens=1500)
                               good for quick iteration and batch generation

    etsy_autonomous.py       — richer 4-part listing (max_tokens=2000):
                               1) Product concept and positioning
                               2) Full SEO-optimized title
                               3) 13 targeted tags
                               4) Complete description with hook, features, CTA
                               better for high-priority hero listings

Both write to outputs/master.txt in the same structured format parseable by
meta_generator.py. Running both on the same brand guide is safe — they share
outputs/executor_state.json, so start fresh (delete state file) if you want
independent runs.

Execution flow
──────────────
  Step 1 — Load brand guide
  Step 2 — Resume or start fresh via executor_state.json
  Step 3 — Initialise outputs/master.txt from prompts/master.txt template
  Step 4 — Weekly loop: generate_listing_content() for each pending task
  Step 5 — Final summary

Outputs
───────
    outputs/master.txt          — structured product listings (parsed by meta_generator.py)
    outputs/week_log.md         — timestamped task execution log
    outputs/executor_state.json — resumable run state

Timing: ~2–5 minutes for a full 4-week run.
"""

import os
import time
from pathlib import Path
from datetime import datetime
from typing import Any, cast

import anthropic
from dotenv import load_dotenv
from rich.console import Console
from rich.panel import Panel
from rich import print as rprint

from common import (
    call_with_retry,
    extract_checklist,
    load_brand_guide,
    load_state,
    save_state,
)
from db import log_run

_ENV_FILE = Path(__file__).resolve().parent.parent / ".env"
load_dotenv(_ENV_FILE)

console = Console()
client  = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])

MODEL               = "claude-haiku-4-5"
_ROOT               = Path(__file__).resolve().parent.parent
BRAND_FILES         = (_ROOT / "outputs" / "brand_guide.md", _ROOT / "brand_guide.md")
STATE_FILE          = _ROOT / "outputs" / "executor_state.json"
LOG_FILE            = _ROOT / "outputs" / "week_log.md"
MASTER_TEMPLATE_FILE = _ROOT / "prompts" / "master.txt"
MASTER_PROMPT_FILE  = _ROOT / "outputs" / "master.txt"
(_ROOT / "outputs").mkdir(exist_ok=True)


def initialize_master_prompt_file() -> None:
    if MASTER_TEMPLATE_FILE.exists():
        template = MASTER_TEMPLATE_FILE.read_text(encoding="utf-8").rstrip()
        MASTER_PROMPT_FILE.write_text(f"{template}\n\n", encoding="utf-8")
        return
    MASTER_PROMPT_FILE.write_text(
        "# Product Listings Master File\n\n"
        f"Generated: {datetime.now().isoformat()}\n\n",
        encoding="utf-8",
    )


def append_master_prompt(week_label: str, task_number: int, task_text: str, prompt: str) -> None:
    entry = (
        f"## {week_label} · Task {task_number}\n"
        f"Task: {task_text}\n\n"
        f"{prompt}\n\n"
        "---\n\n"
    )
    with open(MASTER_PROMPT_FILE, "a", encoding="utf-8") as f:
        f.write(entry)


def generate_listing_content(task: str, guide: str, week: str) -> str:
    response = call_with_retry(lambda: client.messages.create(
        model=MODEL,
        max_tokens=2000,
        system=(
            "You are an autonomous Etsy product content generator for Creator Kit. "
            "Generate complete, ready-to-use Etsy listing content in structured format. "
            "Output MUST follow the exact format below so it can be parsed automatically."
        ),
        messages=[{
            "role": "user",
            "content": (
                f"Week: {week}\n"
                f"Task: {task}\n\n"
                "Brand guide context:\n"
                f"{guide[:3200]}\n\n"
                "Generate Etsy listing content in this EXACT format:\n\n"
                "1. [Product Name] ($[price])\n\n"
                "**Title**: [SEO-optimized Etsy title, max 140 characters]\n\n"
                "**Tags**: [tag1, tag2, tag3, tag4, tag5, tag6, tag7, tag8, tag9, tag10, tag11, tag12, tag13]\n\n"
                "**Full Description**:\n"
                "[Hook sentence addressing buyer pain point]\n\n"
                "What You Get:\n"
                "- [feature 1]\n"
                "- [feature 2]\n"
                "- [feature 3]\n\n"
                "[Benefits paragraph, 2-3 sentences]\n\n"
                "How To Use:\n"
                "1. Download\n"
                "2. Open in Canva\n"
                "3. Customize and publish\n\n"
                "[Call to action sentence]\n\n"
                "---"
            ),
        }],
    ))
    return response.content[0].text.strip()


LABELS = {
    "week_1": "Week 1 — Storefront Setup",
    "week_2": "Week 2 — Listing Expansion",
    "week_3": "Week 3 — External Traffic",
    "week_4": "Week 4 — Optimization",
}


def run_week(key: str, tasks: list[dict[str, Any]], guide: str, state: dict[str, Any]) -> list[dict[str, Any]]:
    label = LABELS[key]
    console.print(Panel(f"[bold]{label}[/bold]", style="cyan"))

    for i, item in enumerate(tasks):
        if item["status"] == "completed":
            console.print(f"  [dim]↳ Skipping: {item['task'][:60]}[/dim]")
            continue

        console.print(f"\n  [bold cyan]Task {i+1}/{len(tasks)}:[/bold cyan] {item['task'][:70]}")
        console.print("  [dim]Generating listing content...[/dim]")

        result = generate_listing_content(item["task"], guide, label)
        rprint(f"\n[bold cyan]--- LISTING CONTENT GENERATED ---[/bold cyan]\n{result}\n")
        append_master_prompt(label, i + 1, item["task"], result)

        item["status"]       = "completed"
        item["result"]       = result[:400]
        item["completed_at"] = datetime.now().isoformat()

        with open(LOG_FILE, "a", encoding="utf-8") as f:
            f.write(f"\n## {label} · Task {i+1}\n**Task:** {item['task']}\n**Result:** {result[:300]}\n---\n")

        state["checklist"][key] = tasks
        save_state(STATE_FILE, state)
        console.print(f"  [green]✓ Task {i+1} complete[/green]")
        time.sleep(2)

    return tasks


def main() -> None:
    console.print(Panel(
        "[bold]Creator Kit — Autonomous Listing Generator[/bold]\n"
        f"[dim]{MODEL} · outputs/brand_guide.md → outputs/master.txt[/dim]",
        style="cyan",
    ))

    guide = load_brand_guide(BRAND_FILES)

    state: dict[str, Any] = cast(dict[str, Any], load_state(STATE_FILE)) or {}
    if state:
        console.print("[yellow]Resuming from saved state.[/yellow]")
        if not MASTER_PROMPT_FILE.exists():
            initialize_master_prompt_file()
    else:
        checklist: dict[str, list[dict[str, Any]]] = extract_checklist(guide)
        state = {"started_at": datetime.now().isoformat(), "checklist": checklist}
        save_state(STATE_FILE, state)
        initialize_master_prompt_file()
        console.print("[green]New execution started.[/green]")

    week_checklist: dict[str, list[dict[str, Any]]] = state.get("checklist", {})
    for key in ["week_1", "week_2", "week_3", "week_4"]:
        tasks: list[dict[str, Any]] = week_checklist.get(key, [])
        if not tasks:
            console.print(f"[dim]No tasks for {key}[/dim]")
            continue
        if all(t["status"] == "completed" for t in tasks):
            console.print(f"[dim]{LABELS[key]} already complete[/dim]")
            continue
        week_checklist[key] = run_week(key, tasks, guide, state)
        state["checklist"] = week_checklist
        console.print(f"\n[green]✓ {LABELS[key]} complete[/green]\n")
        time.sleep(3)

    done  = sum(1 for v in week_checklist.values() for t in v if t["status"] == "completed")
    total = sum(len(v) for v in week_checklist.values())
    log_run("autonomous_executor", "etsy_autonomous", "success", f"Tasks completed: {done}/{total}")
    console.print(Panel(
        f"[bold green]Launch complete[/bold green]\n\n"
        f"Tasks: {done}/{total}\n"
        f"Log: outputs/week_log.md\n"
        f"Master prompts: outputs/master.txt",
        style="green",
    ))


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        log_run("autonomous_executor", "etsy_autonomous", "failed", str(exc))
        raise
